Task2 - Create a brain for calculator (MVC)
olegmyatlikov/CalculatorObjC pull request #4
Opened 2017-05-25 19:53 UTC by olegmyatlikov

2017-05-29 10:15 UTC, imironenko requested changes

2017-05-29 10:15 UTC, imironenko commented on CalculatorObjC/CalculatorModel.m
> +                                      return (int)firstValue % (int)secondValue;
Данная операция возможно и над дробными значениями. См. "Вещественные числа" https://ru.wikipedia.org/wiki/Деление_с_остатком

2017-05-29 10:15 UTC, imironenko commented on CalculatorObjC/CalculatorModel.m
> +        self.reservedOperation = [self.binaryOperations valueForKey:operation];
Работая со словарям, стоит использовать `[self.binaryOperations objectForKey:operation];` или `self.binaryOperations[operation];`

2017-05-29 10:15 UTC, imironenko commented on CalculatorObjC/CalculatorModel.m
> +        double (^unaryOperation)(double) = [self.unaryOperations valueForKey:operation];
аналогично комментарию выше

2017-05-29 10:15 UTC, imironenko commented on CalculatorObjC/CalculatorModel.m
> +        self.operand = [[self.constants valueForKey:operation] doubleValue];
аналогично

2017-05-29 10:15 UTC, imironenko commented on CalculatorObjC/ViewController.m
> +- (IBAction)setOperationButtonPressed:(UIButton *)sender {
Не используй `set` префикс, затрудняет читабельность

2017-05-29 10:15 UTC, imironenko commented on CalculatorObjC/ViewController.m
> +        if (![sender.currentTitle isEqual:@"0"]) {
Давай вынесем `@"0"` в константу

2017-05-29 10:15 UTC, imironenko commented on CalculatorObjC/ViewController.m
> +        self.calculatorModel.readyToCalc = YES; // fix case (8/0+)
Давай попробуем убрать установку `readyToCalc` в контроллере, пусть модель решает когда считать. Замечание: можно добавить установку значения `readyToCalc` в метод `setOperand:`

2017-05-29 10:15 UTC, imironenko commented on CalculatorObjC/CalculatorModel.m
> +        self.waitSecondOperand = NO;
не надо использовать `self` в `init`-методе

2017-05-29 11:56 UTC, imironenko commented on CalculatorObjC/CalculatorModel.m
> +        self.binaryOperations = @{@"+" : ^ double (double firstValue, double secondValue) {
Давай добавим константы для keys

2017-05-30 07:43 UTC, olegmyatlikov commented on CalculatorObjC/CalculatorModel.m
> +        self.binaryOperations = @{@"+" : ^ double (double firstValue, double secondValue) {
Для всех keys? @"+" = *const plusConst, @"sin" = sinConst и т.д.? Просто так, как есть более читабельно мне кажется...

2017-05-30 08:19 UTC, imironenko commented on CalculatorObjC/CalculatorModel.m
> +        self.binaryOperations = @{@"+" : ^ double (double firstValue, double secondValue) {
читабельность не будет затрудняться, наименование должно быть в соответствие с код стайлом, напр. `<Project_prefix>CalculatorSinOperation, <Project_prefix>CalculatorAddOperation`

2017-05-31 07:53 UTC, imironenko requested changes

2017-05-31 07:53 UTC, imironenko commented on CalculatorObjC/CalculatorModel.m
> +        [_binaryOperations retain];
Лучше так не делать, давай сделаем retain непосредственно при присвоение значения выше `_binaryOperations = [@{...} retain]`

2017-05-31 07:53 UTC, imironenko commented on CalculatorObjC/CalculatorModel.m
> +        [_unaryOperations retain];
аналогично

2017-05-31 07:53 UTC, imironenko commented on CalculatorObjC/CalculatorModel.m
> +        [_constants retain];
аналогично

2017-05-31 07:53 UTC, imironenko commented on CalculatorObjC/CalculatorModel.m
> +    if ([self.displayResult isEqualToString:@"inf"] || [self.displayResult isEqualToString:@"nan"]) {
Давай и для этих значений сделаем константы `inf, nan, error`

2017-05-31 07:53 UTC, imironenko commented on CalculatorObjC/CalculatorModel.m
> +    } else if ([operation isEqualToString:@"="]) {
Давай для "=" и "AC" создадим константы

2017-05-31 07:53 UTC, imironenko commented on CalculatorObjC/ViewController.m
> +    if (![self.displayLabel.text containsString:@"."]) {
Будет неплохо "."  сделать константой

2017-05-31 07:53 UTC, imironenko commented on CalculatorObjC/ViewController.m
> +        self.displayLabel.text = [NSString stringWithFormat:@"%@.", self.displayLabel.text];
и использовать здесь константное значение для "."

2017-05-31 07:53 UTC, imironenko commented on Constants.h
> +@interface Constants : NSObject
Не критично, такое объявление констант возможно, но, зачастую, используется без выноса в отдельный класс.

Давай  сделаем константы как предлагают в  https://github.com/NYTimes/objective-c-style-guide#constants 

`static NSString * const NYTAboutViewControllerCompanyName = @"The New York Times Company";
static const CGFloat NYTImageThumbnailHeight = 50.0;`

2017-05-31 09:36 UTC, imironenko approved these changes

2017-05-31 09:36 UTC, imironenko commented
👍

2017-05-31 09:42 UTC, merged